site_name: Once Human Wiki
site_url: https://francusik.github.io/once-human-wiki/
repo_url: https://github.com/FrancUsik/once-human-wiki
theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
nav:
  - Главная: index.md
  - База статей: once_human_md/index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FrancUsik/once-human-wiki
use_directory_urls: true
