name: Deploy MkDocs (Material)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs Material
        run: pip install mkdocs mkdocs-material pymdown-extensions

      - name: Generate article index
        run: |
          python - << 'PY'
          import os, pathlib, urllib.parse

          root = pathlib.Path('docs/once_human_md')
          root.mkdir(parents=True, exist_ok=True)

          lines = ['# База статей Once Human', '']
          for p in sorted(root.glob('*.md'), key=lambda x: x.name.lower()):
              if p.name.lower() == 'index.md':
                  continue
              title = p.stem
              url = './' + urllib.parse.quote(p.name)   # экранируем пробелы и спецсимволы
              lines.append(f'- [{title}]({url})')

          (root / 'index.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
          PY

      - name: Build site
        run: mkdocs build --site-dir site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
